---
abstract: 'Trivial File Transfer Protocol daemon'
author:
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-TFTPd
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 3.0
resources:
  bugtracker: https://github.com/jhthorsen/mojo-tftpd/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jhthorsen/mojo-tftpd
version: 0.01
