---
abstract: 'Trivial File Transfer Protocol daemon'
author:
  - 'Svetoslav Naydenov <harryl@cpan.org>'
  - 'Jan Henning Thorsen <jhthorsen@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojo-TFTPd
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: 4.30
resources:
  bugtracker: https://github.com/jhthorsen/mojo-tftpd/issues
  homepage: https://github.com/jhthorsen/mojo-tftpd
  repository: https://github.com/jhthorsen/mojo-tftpd.git
version: 0.04
